---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: true
  state_top:
    base:
      '*':
        - init
  pillars:
    top.sls:
      base:
        "*":
          - testing
    testing.sls:
      iam:
        access_key: AKIAJF2Q7WK3WOIB7MAA
        secret_key: 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
  grains:
    customer: bar

platforms:
  - name: centos-7.3


suites:
  - name: default
