---
driver:
  name: vagrant

platforms:
  - name: centos/7

provisioner:
  name: salt_solo
  is_file_root: true
  salt_copy_filter:
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
  state_top:
    base:
      '*':
        - extenda-repo
  grains:
    customer: test-customer

suites:
  - name: default
