---
driver:
  name: vagrant

platforms:
  - name: centos-7.3

provisioner:
  name: salt_solo
  is_file_root: true
  salt_copy_filter:
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
  state_top:
    base:
      '*':
        - extenda-repo
  grains:
    customer: test-customer

suites:
  - name: default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - vault
      pillars-from-files:
        vault.sls: vault.sls
  - name: channel-develop
    provisioner:
      pillars-from-files:
        vault.sls: vault.sls
      pillars:
        top.sls:
          base:
            '*':
              - vault
              - channels
        channels.sls:
          extenda_repo:
            channels:
              - develop
