---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: true
  state_top:
    base:
      '*':
        - extenda-repo
  pillars:
    top.sls:
      base:
        "*":
          - extenda-repo
  grains:
    customer: bar

platforms:
  - name: centos-7.3


suites:
  - name: default
    provisioner:
      pillars-from-files:
        extenda-repo.sls: test/pillar/iam.sls
