---
driver:
  name: vagrant

platforms:
  - name: centos-7.3

provisioner:
  name: salt_solo
  is_file_root: true
  salt_copy_filter:
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
  state_top:
    base:
      '*':
        - extenda-repo
  pillars:
    top.sls:
      base:
        "*":
          - vault
  grains:
    customer: bar

suites:
  - name: default
    provisioner:
      pillars-from-files:
        vault.sls: vault.sls
